export const CREATE_HERO = 'CREATE_HERO';
export const CREATE_HERO_FAIL = 'CREATE_HERO_FAIL';
export const CREATE_HERO_SUCCESS = 'CREATE_HERO_SUCCESS';

export const DELETE_HERO = 'DELETE_HERO';

export const FETCH_HEROES = 'FETCH_HEROES';
export const FETCH_HEROES_FAIL = 'FETCH_HEROES_FAIL';
export const FETCH_HEROES_SUCCESS = 'FETCH_HEROES_SUCCESS';

export const GET_HERO = 'GET_HERO';

export const UPDATE_HERO = 'UPDATE_HERO';
export const UPDATE_HERO_FAIL = 'UPDATE_HERO_FAIL';
export const UPDATE_HERO_SUCCESS = 'UPDATE_HERO_SUCCESS';
